services:
  database:
    container_name: database
    image: postgres:17.4-alpine3.21
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - task_cloud_network
    ports:
      - "${POSTGRES_PORT}:5432"

  frontend:
    build: ./frontend
    container_name: frontend
    restart: unless-stopped
    networks:
      - task_cloud_network
    ports:
      - "${VITE_PORT}:5173"
    volumes:
      - ./frontend:/app

  node-backend:
    build: ./backend/node
    container_name: node_backend
    restart: unless-stopped
    depends_on:
      - database
    env_file:
      - .env
    networks:
      - task_cloud_network
    ports:
      - "${NODE_PORT}:3000"
    volumes:
      - ./backend/node:/app

networks:
  task_cloud_network:
    driver: bridge
    name: task_cloud_network
